export const actionTypes = {
  FETCH_AUTORS_REQUEST: 'FETCH_AUTORS_REQUEST',
  FETCH_AUTORS_SUCCESS: 'FETCH_AUTORS_SUCCESS',
  FETCH_AUTORS_ERROR: 'FETCH_AUTORS_ERROR',

  FETCH_EDITORAS_REQUEST: 'FETCH_EDITORAS_REQUEST',
  FETCH_EDITORAS_SUCCESS: 'FETCH_EDITORAS_SUCCESS',
  FETCH_EDITORAS_ERROR: 'FETCH_EDITORAS_ERROR',

  FETCH_AUTORS_DELETE: 'FETCH_AUTORS_DELETE',

  FETCH_AUTOR_ITEM_REQUEST: 'FETCH_AUTOR_ITEM_REQUEST',
  FETCH_AUTOR_ITEM_SUCCESS: 'FETCH_AUTOR_ITEM_SUCCESS',
  FETCH_AUTOR_ITEM_ERROR: 'FETCH_AUTORS_ERROR',
};

export const endpoints = {
  AUTORS: 'http://localhost:8000/api/autors',
  AUTOR_ITEM: 'http://localhost:8000/api/autors',
  GENEROS_LITERARIOS: 'http://localhost:8000/api/generos',
  EDITORAS: 'http://localhost:8000/api/editoras',
};
