export const actionTypes = {
  FETCH_AUTORS_REQUEST: 'FETCH_AUTORS_REQUEST',
  FETCH_AUTORS_SUCCESS: 'FETCH_AUTORS_SUCCESS',
  FETCH_AUTORS_ERROR: 'FETCH_AUTORS_ERROR',
  FETCH_AUTORS_DELETE: 'FETCH_AUTORS_DELETE',

  FETCH_AUTOR_ITEM_REQUEST: 'FETCH_AUTOR_ITEM_REQUEST',
  FETCH_AUTOR_ITEM_SUCCESS: 'FETCH_AUTOR_ITEM_SUCCESS',
  FETCH_AUTOR_ITEM_ERROR: 'FETCH_AUTOR_ITEM_ERROR',

  FETCH_EDITORAS_REQUEST: 'FETCH_EDITORAS_REQUEST',
  FETCH_EDITORAS_SUCCESS: 'FETCH_EDITORAS_SUCCESS',
  FETCH_EDITORAS_ERROR: 'FETCH_EDITORAS_ERROR',
  FETCH_EDITORAS_DELETE: 'FETCH_EDITORAS_DELETE',

  FETCH_EDITORA_ITEM_REQUEST: 'FETCH_EDITORA_ITEM_REQUEST',
  FETCH_EDITORA_ITEM_SUCCESS: 'FETCH_EDITORA_ITEM_SUCCESS',
  FETCH_EDITORA_ITEM_ERROR: 'FETCH_EDITORA_ITEM_ERROR',

  FETCH_GENEROS_REQUEST: 'FETCH_GENEROS_REQUEST',
  FETCH_GENEROS_SUCCESS: 'FETCH_GENEROS_SUCCESS',
  FETCH_GENEROS_ERROR: 'FETCH_GENEROS_ERROR',
  FETCH_GENEROS_DELETE: 'FETCH_GENEROS_DELETE',

  FETCH_GENERO_ITEM_REQUEST: 'FETCH_GENERO_ITEM_REQUEST',
  FETCH_GENERO_ITEM_SUCCESS: 'FETCH_GENERO_ITEM_SUCCESS',
  FETCH_GENERO_ITEM_ERROR: 'FETCH_GENERO_ITEM_ERROR',

  FETCH_LIVROS_REQUEST: 'FETCH_LIVROS_REQUEST',
  FETCH_LIVROS_SUCCESS: 'FETCH_LIVROS_SUCCESS',
  FETCH_LIVROS_ERROR: 'FETCH_LIVROS_ERROR',
  FETCH_LIVROS_DELETE: 'FETCH_LIVROS_DELETE',

  FETCH_LIVRO_ITEM_REQUEST: 'FETCH_LIVRO_ITEM_REQUEST',
  FETCH_LIVRO_ITEM_SUCCESS: 'FETCH_LIVRO_ITEM_SUCCESS',
  FETCH_LIVRO_ITEM_ERROR: 'FETCH_LIVRO_ITEM_ERROR',

  SHOW_FORM: 'SHOW_FORM',

  GENERO_FORM_REQUEST: 'GENERO_FORM_REQUEST',
  GENERO_FORM_SUCCESS: 'GENERO_FORM_SUCCESS',
  GENERO_FORM_ERROR: 'GENERO_FORM_ERROR',

  EDITORA_FORM_REQUEST: 'EDITORA_FORM_REQUEST',
  EDITORA_FORM_SUCCESS: 'EDITORA_FORM_SUCCESS',
  EDITORA_FORM_ERROR: 'EDITORA_FORM_ERROR',

  AUTOR_FORM_REQUEST: 'AUTOR_FORM_REQUEST',
  AUTOR_FORM_SUCCESS: 'AUTOR_FORM_SUCCESS',
  AUTOR_FORM_ERROR: 'AUTOR_FORM_ERROR',

  LIVRO_FORM_REQUEST: 'LIVRO_FORM_REQUEST',
  LIVRO_FORM_SUCCESS: 'LIVRO_FORM_SUCCESS',
  LIVRO_FORM_ERROR: 'LIVRO_FORM_ERROR',

  LIVRO_UPDATE_REQUEST: 'LIVRO_UPDATE_REQUEST',
  LIVRO_UPDATE_SUCCESS: 'LIVRO_UPDATE_SUCCESS',
  LIVRO_UPDATE_ERROR: 'LIVRO_UPDATE_ERROR',
};

export const endpoints = {
  AUTORS: 'http://localhost:8000/api/autors',
  AUTOR_ITEM: 'http://localhost:8000/api/autors',
  GENEROS_LITERARIOS: 'http://localhost:8000/api/generos',
  EDITORAS: 'http://localhost:8000/api/editoras',
  LIVROS: 'http://localhost:8000/api/livros',
};
